### ISSUE TITLE
Not compatible with gnome 3.26

### ISSUE THREAD

**Issue by yurividal** [ikalnytskyi/gnome-shell-extension-icon-hider#28]
Please update the extension. =)

**Comment by ikalnytskyi** [comment]
Thanks for the reporting an issue and sorry for the delay. Unfortunately, I don't have Linux machine around and won't have one for a few days. I'll try to update the extension once I have an opportunity.

**Comment by ikalnytskyi** [comment]
Apparently since GNOME Shell 3.26 the status area (aka tray) is not shown by default. This effectively means that there's no reason to exist for extensions like Icon Hider.

For those who by some reason wants to continue use Icon Hider I prepare a patch that won't be merged but could be applied manually.

```diff
diff --git a/icon-hider@kalnitsky.org/_compat.js b/icon-hider@kalnitsky.org/_compat.js
index a9c106b..32602da 100644
--- a/icon-hider@kalnitsky.org/_compat.js
+++ b/icon-hider@kalnitsky.org/_compat.js
@@ -14,8 +14,13 @@
  * The function returns a tray manager instance.
  */
 function getTrayManager() {
+    const Shell = imports.gi.Shell;
     const Main = imports.ui.main;

+    if (Shell.TrayManager) {
+      return new Shell.TrayManager();
+    }
+
     // various gnome versions have various tray keepers. let's find all
     // available tray keepers and then find tray manager instance among
     // them.
diff --git a/icon-hider@kalnitsky.org/metadata.json b/icon-hider@kalnitsky.org/metadata.json
index f1852a3..6aba6bd 100644
--- a/icon-hider@kalnitsky.org/metadata.json
+++ b/icon-hider@kalnitsky.org/metadata.json
@@ -1,5 +1,5 @@
 {
-    "shell-version": ["3.10", "3.12", "3.14", "3.16", "3.18", "3.20", "3.22"],
+    "shell-version": ["3.10", "3.12", "3.14", "3.16", "3.18", "3.20", "3.22", "3.26"],
     "uuid": "icon-hider@kalnitsky.org",
     "name": "Icon Hider",
     "description": "Show/Hide icons from top panel",
```

Sorry for inconvenience, I neither have time nor desire to evolve Icon Hider into full feature status area management extension.

**Comment by theychx** [comment]
@ikalnytskyi 
I volunteer to keep **Icon Hider** on life support if you are interested. I have no developer interest in gnome shell, but would like to do minimal maintenance, as I use this extension myself. I have the same username on gnome.org (where I maintain [another](https://extensions.gnome.org/extension/1116/workspace-switch-wraparound/) otherwise abandoned extension).

**Comment by ikalnytskyi** [comment]
@theychx great! I'd transfer the ownership of Icon Hider on [extensions.gnome.org](https://extensions.gnome.org/extension/351/icon-hider/) but didn't find the way to do it. Do you want to develop in your own fork, or you prefer to commit into this repo?

**Comment by theychx** [comment]
It seems like forking is the only viable option, as it indeed seems that there is no way no transfer ownership of extensions on extensions.gnome.org (not even an email-address which is just crazy).
So I'll fork this repo, apply the patch and submit this as my own user. The extensions.gnome.org reviewer will then request your approval at some point. I'll keep you posted.

**Comment by ikalnytskyi** [comment]
@theychx sure. I'll backlink your extension once it's ready.

**Comment by maweki** [comment]
If you agree on transfer of ownership you can send an email to the shell-list and request this transfer with documentation of the transfer.

Then the new owner can upload a new version of the original extension. I will not approve the new upload by @theychx but I am happy that the project found a new maintainer.

I will keep track of this issue. :)

**Comment by ikalnytskyi** [comment]
@maweki I'd say I'll do whatever suits better for @theychx. :)

**Comment by maweki** [comment]
It's a gnome issue. We generally don't allow forks, when there's not a really good reason. So we prefer that contributors either work with upstream or (if that's not possible because upstream is abandoned) we change on our end what we consider upstream for an extension to be.

It happens almost weekly that I send developers upstream when they try to add an extension that is a fork of something with just one feature added or something.

Glad to see that you agree on how to proceed with the project :)

**Comment by theychx** [comment]
@maweki I'm a bit confused now, what exactly is it you want us to do? And why isn't this ticket in itself proof that @ikalnytskyi wants to transfer ownership to me?

**Comment by maweki** [comment]
I currently don't have the permissions to just do the transfer myself. Please write an email to the shell-list describing who you want to transfer the extension to, with a link to this ticket here (which is proof of  intention).

**Comment by theychx** [comment]
@ikalnytskyi Please send an email to gnome-shell-list@gnome.org (and reference this ticket), so we can get the ball rolling.

**Comment by ikalnytskyi** [comment]
Just want to let you know guys that I sent an email to gnome-shell-list@gnome.org yesterday. Since I'm not subscribed to gnome-shell-list, it needs to be approved by mail list moderator.

It seems not there though. :(

https://mail.gnome.org/archives/gnome-shell-list/2017-October/thread.html

**Comment by theychx** [comment]
@maweki It's been 14 days now, and ikalnytskyi's mail still hasn't appeared on the list. Is there anything you can do?

**Comment by maweki** [comment]
I am currently quite busy and I also don't like this workflow. I see what I can do. :)

**Comment by maweki** [comment]
I now have the correct rights to do the transfer myself now. Just hang on tight for just a little bit and I'll do the transfer. Just have to figure out the ui myself :)

Thank you all for your understanding and thanks for working with upstream.

**Comment by ikalnytskyi** [comment]
@maweki thanks for your help! :)

**Comment by maweki** [comment]
Okay, the transfer should now be complete. Sorry for the long delay. :(

**Comment by theychx** [comment]
@ikalnytskyi Please give me write access to this repo, so I can get a new version out.

@maweki Thank you for your help.

**Comment by ikalnytskyi** [comment]
@theychx permissions granted. I can transfer the whole repo to you if you like.
